entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"


api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: "conf.d"

certificatesResolvers:
  myresolver:
    acme:
      dnschallenge:
        provider: cloudflare
